### ISSUE TITLE
Compilation Failure on kernel 4.0.5 gcc 4.8.4

### ISSUE THREAD

**Issue by guspower** [chenhaiq/mt7610u_wifi_sta_v3002_dpo_20130916#1]
Hi,

I'm getting compilation failures when trying to make under kernel 4.0.5 gcc 4.8.4

    mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../os/linux/sta_ioctl.c:2364:2: error: unknown field ‘num_private’ specified in initializer
        .num_private  = N(rt_priv_handlers),

Any ideas about how I can get it to compile cleanly?

Cheers,

G

**Comment by madrat-** [comment]
works well with 4.1.10-200.fc22.x86_64

**Comment by StephaneP** [comment]
will this work on ubuntu 15.10?

**Comment by Edenhofer** [comment]
Probably. I can confirm that it is working with linux from version 4.2.5 to 4.4.5 and gcc from version 5.2.0 to 5.3.0 on Arch Linux.

**Comment by guspower** [comment]
Confirmed - master now builds successfully against gcc version 4.9.3, kernel 4.1.15
