### ISSUE TITLE
Not works with 4.6 kernel (compile errors)

### ISSUE THREAD

**Issue by colorprint** [chenhaiq/mt7610u_wifi_sta_v3002_dpo_20130916#5]
`In file included from /home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/include/rtmp_os.h:44:0,
                 from /home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/include/rtmp_comm.h:75,
                 from /home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/include/rt_config.h:33,
                 from /home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../chips/rtmp_chip.c:28:
/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/include/os/rt_linux.h:77:0: warning: "EXT_BUILD_CHANNEL_LIST" redefined
 #define EXT_BUILD_CHANNEL_LIST  /* must define with CRDA */
 
<command-line>:0:0: note: this is the location of the previous definition
/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../chips/rtmp_chip.c: In function 'RtmpChipOpsHook':
/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../chips/rtmp_chip.c:910:30: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  pChipOps->ChipSwitchChannel = Default_ChipSwitchChannel;
                              ^
cc1: some warnings being treated as errors
scripts/Makefile.build:291: recipe for target '/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../chips/rtmp_chip.o' failed
make[2]: *** [/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../chips/rtmp_chip.o] Error 1
Makefile:1428: recipe for target '_module_/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux' failed
make[1]: *** [_module_/home/TMP/mt7610u/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.6.0-rc7-mainline/build'
Makefile:403: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2
`

**Comment by xf0e** [comment]
I can confirm this issue.

**Comment by lothar-mar** [comment]
me too.

**Comment by ase34** [comment]
can confirm, does someone have a solution?

**Comment by reneploetz** [comment]
I just created a pull request for this issue that fixes the compile errors (they were warnings before). It seems to work on my system, tough I performed only limited testing.

**Comment by ReekyStive** [comment]
I still have the same problem now!
Ubuntu 18.04
gcc 7.4.0
